# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b48154d73bb863ea1e7bfec0e3bfc1638d019ed4bafd6257d1cdedf0513396687c175ada33bb3737b9353333ab4e347765b02953a5fd7268d7855017ebe9c337

test:
  secret_key_base: b5d4c87ebd954b23cd6c6860810dc607f32f6536e6938d6784aebcb38d7e2841daeba4fae545b1a4107d5557c83ed0d15bf326b9f1b1f028e4cd14fd1e95fb90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
